// data/matches.ts
export const matches = [
  {
    id: '1',
    league: 'CBF',
    date: 'Dom 27/04 16:00',
    team1: 'fut1',
    team2: 'fut2',
    logo1: require('../assets/fut1.png'),
    logo2: require('../assets/fut2.png'),
  },
  {
    id: '2',
    league: 'CBF',
    date: 'Dom 27/04 12:30',
    team1: 'fut5',
    team2: 'fut6',
    logo1: require('../assets/fut5.png'),
    logo2: require('../assets/fut6.png'),
  },
  {
    id: '3',
    league: 'NBA',
    date: 'Tue 22/04 19:00',
    team1: 'nba1',
    team2: 'nba2',
    logo1: require('../assets/nba1.png'),
    logo2: require('../assets/nba2.png'),
  },
  {
    id: '4',
    league: 'NHL',
    date: 'Sun 20/04 14:00',
    team1: 'nhl1',
    team2: 'nhl2',
    logo1: require('../assets/nhl1.png'),
    logo2: require('../assets/nhl2.png'),
  },
  {
  id: '5',
  league: 'NBA',
  date: 'Seg 28/04 18:00',
  closeTime: '17:55:00',
  team1: 'nba2',
  team2: 'nba1',
  logo1: require('../assets/nba2.png'),
  logo2: require('../assets/nba1.png'),
},
{
  id: '6',
  league: 'NHL',
  date: 'Ter 29/04 20:00',
  closeTime: '19:45:00',
  team1: 'nhl2',
  team2: 'nhl1',
  logo1: require('../assets/nhl2.png'),
  logo2: require('../assets/nhl1.png'),
}

];
